apple/swift-openapi-urlsession

.github/release.yml

We want to provide consistent and comprehensive release notes when making
a release. Github supports generating draft release notes based on labels
attached to PRs to make this simpler.
- Add .github/release.yml with SemVer based release notes sections.
When creating a release, Github should populate the release notes based on the
PRs that have been merged since the last release and group them based on their
labels.
None.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

Add .github/release.yml to automate drafting release notes

---

Package.swift

Unfortunately until we adopt 5.9, adding ExistentialAny on upstream packages has unintended consequences for some downstream packages, so disabling for now. Details in https://github.com/apple/swift-openapi-generator/issues/120
Disabled the feature enforcement, but the code changes are there, so downstream adopters can still use them.
We won't be seeing the issue described in https://github.com/apple/swift-openapi-generator/issues/120.
PR CI, which discovered the original issue.

Disable ExistentialAny temporarily

---

Package.swift

Runtime 0.2.0 is compatible with 0.1.3+ in the APIs adopted in the transport, so just reflect that in the manifest.
Increased the supported runtime range to include 0.2.x.
Once released, folks will be able to use 0.1.x of this transport with both 0.1.x and 0.2.x of runtime.
Will be manually tested once runtime 0.2.0 is released.

Prepare being compatible with runtime 0.2.0 release

---

Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

Fixes https://github.com/apple/swift-openapi-generator/issues/251.
Use the already escaped path setter on `URLComponents` to avoid the second encoding pass.
Path parameters that needed escaping are only escaped once, not twice.
Adapted the existing unit test to cover a path item that needs escaping.

Fix double encoding of path parameters

---

.swift-format
Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/Locking.swift

- Relates to https://github.com/apple/swift-openapi-generator/issues/165
- Enable new rules in swift-format and address changes required
- New swift format rules will be implemented
- Run the tests

Enable documentation comment validation in swift-format

---

Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift
docker/Dockerfile

As per https://github.com/apple/swift-openapi-generator/issues/175.
Bumped swift-format for CI, no other changes needed.
Using swift-format 5.9.
Soundness passed.

Bump swift-format to 5.9

---

.swift-format
Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/Locking.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

- Relates to [#230](https://github.com/apple/swift-openapi-generator/issues/230)
- Disable respectsExistingLineBreaks .swift-format rule and address changes requested
- One of the .swift-format rules will be disabled
- Run Tests

Disable "respectsExistingLineBreaks" in .swift-format for more consistent styling

---

Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/HTTPBodyOutputStreamTests.swift
Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/URLSessionBidirectionalStreamingTests.swift

The tests fail to compile on anything older than macOS 13, because they
use a number of APIs only available in macOS 13+:
- `Duration`
- `Task.sleep(for:)`
- `DispatchQueue.asyncAndWait` (closure variant)
Use the following APIs instead:
- `NIO.TimeInterval` (we have NIO dependency in tests already).
- `Task.sleep(nanoseconds:)`
- `DispatchQueue.asyncAndWait(execute:)`
Tests can be built on older platforms.

Use APIs available on older macOS in tests

---

Sources/OpenAPIURLSession/AsyncBackpressuredStream/AsyncBackpressuredStream.swift
Tests/OpenAPIURLSessionTests/AsyncBackpressuredStreamTests/AsyncBackpressuredStreamTests.swift

Some of our bidirectional streaming tests were failing intermittently. When they failed, the symptom was that more bytes were received by the end user (in the test) than the server sent.
For example, in the test `testStreamingDownload_1kChunk_10kChunks_100BDownloadWatermark`, we expect:
- ✅ The server sends 10,000 chunks of 1024 bytes:
```console
❯ cat repro.txt | grep -i "server sent body chunk" | head -3
Server sent body chunk 1/10000 of 1024
Server sent body chunk 2/10000 of 1024
Server sent body chunk 3/10000 of 1024
❯ cat repro.txt | grep -i "server sent body chunk" | wc -l
10000
```
- ✅ URLSession `didReceive data` callback called a non-deterministic number of times because it may re-chunk the bytes internally, but the total number of bytes through the delegate calls is 10,240,000: …

Add missing transition AsyncBackpressuredStream state machine

---

Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/AsyncBackpressuredStreamTests/AsyncBackpressuredStreamTests.swift
Tests/OpenAPIURLSessionTests/NIOAsyncHTTP1TestServer.swift
Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/HTTPBodyOutputStreamTests.swift
Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/MockInputStreamDelegate.swift
Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/URLSessionBidirectionalStreamingTests.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

The transport code has some debug logging, which is compile-time omitted in release builds, and only enabled in tests.
A number of tests produce an enormous amount of output (e.g. the streaming tests that pull 10GB through 10MB buffers), which are unwieldy in CI and locally.
Additionally, we found that the logging produced by these tests had interleaved output, both because of the mixed use of `print` and `debug` in tests and the lack of locking between multiple threads
Finally, even when running in debug mode with debug logging _disabled_, the function arguments to the `debug` function were still evaluated unnecessarily.
- Update the `debug` function to log to standard error (cf. standard out).
- Pass an autoclosure as argument to `debug` so that it is only evaluated when logging is …

Improve debug logging and add tests that it is not evaluated when disabled

---

Package.swift
Sources/OpenAPIURLSession/BufferedStream/BufferedStream.swift
Sources/OpenAPIURLSession/BufferedStream/Lock.swift

Make module compile with LE.
Make a few symbols not inlinable, just usable from inline.
Builds with LE.
Built locally.

Improve inlining

---

Package.swift
Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/URLSessionBidirectionalStreamingTests/HTTPBodyOutputStreamTests.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

On main, the HTTPBody length type changed from Int to Int64.
Adapted the transport with this change.
Repo builds again when using the latest runtime.
Adapted tests.

Prep for 1.0 alpha, adapted to runtime changes in main

---

Tests/OpenAPIURLSessionTests/TestUtils.swift

We had some code in an `#if swift(<5.9)` block, which can now be removed because we only support Swift 5.9 and newer.
Remove code required to support Swift 5.8.
Removed dead code.
Tests pass.

Remove AsyncStream.makeStream backports now we support only Swift 5.9+

---

Sources/OpenAPIURLSession/URLSessionTransport.swift

Super-minor PR - was reading the source and a typo was messing with me, so I thought I'd provide an update to resolve it. No functional changes, just the typo fix.

fixes internal typo in source parameter

---

Sources/OpenAPIURLSession/URLSessionBidirectionalStreaming/URLSession+Extensions.swift
Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/TaskCancellationTests.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

In our fallback, buffered implementation, we did not use a task cancellation handler so were not proactively cancelling the URLSession task when the Swift concurrency task was cancelled. Additionally, while we _did_ have a task cancellation handler in the streaming implementation, so the URLSession task would be cancelled, we were not actively checking for task cancellation as often as we could.
- Added more cooperative task cancellation.
- Added tests for both implementations that when the parent task for the client request is cancelled that we get something sensible. Note that in some cases, the request will succeed. In the cases where the request fails, it will surface as a `ClientError` to the user where the `underlyingError` is either `Swift.CancellationError` or `URLError` with …

More checks for task cancellation and tests

---

Sources/OpenAPIURLSession/URLSessionBidirectionalStreaming/HTTPBodyOutputStreamBridge.swift

When running the cancellation tests in a loop, very occasionally there would be a crash with the following backtrace:
```
#0	0x000000018aa008d4 in objc_opt_respondsToSelector ()
#1	0x000000018aea3410 in _outputStreamCallbackFunc ()
#2	0x000000018aea3310 in _signalEventSync ()
#3	0x000000018aeecdb0 in ___signalEventQueue_block_invoke ()
#4	0x000000018abe6cb8 in _dispatch_call_block_and_release ()
#5	0x000000018abe8910 in _dispatch_client_callout ()
#6	0x000000018abefea4 in _dispatch_lane_serial_drain ()
#7	0x000000018abf0a08 in _dispatch_lane_invoke ()
#8	0x000000018abfb61c in _dispatch_root_queue_drain_deferred_wlh ()
#9	0x000000018abfae90 in _dispatch_workloop_worker_thread ()
#10	0x000000018ad96114 in _pthread_wqthread ()
```
This seems to indicate that the output stream is trying to …

Set OutputStream.delegate to nil in HTTPBodyOutputStreamBridge.deinit

---

Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/URLSessionTransportTests.swift

Fix the translation between Foundation types and HTTP types.
The code is mostly borrowed from swift-http-types:
https://github.com/apple/swift-http-types/tree/main/Sources/HTTPTypesFoundation
Translates the string encoding (URLSession expects ISOLatin1) and handles multi-value fields.
Should address the cookie issue among other issues.
All existing tests still pass.

Fix request and response translation

---

Sources/OpenAPIURLSession/BufferedStream/Lock.swift

Motivation:
The 'unsafeDowncast' can cause a miscompile leading to unexpected runtime behaviour.
Modifications:
- Use 'as!' instead
Result:
No miscompiles on 5.10

Change 'unsafeDowncast' to 'as!'

---

Sources/OpenAPIURLSession/URLSessionTransport.swift

The `public` modifier of members in an extension of an internal type doesn't actually make them public, and can be confusing when reading the code.
Remove the public modifiers.
Less confusing code.
Tests still pass.

Remove public modifiers from an internal extension

---

.swiftformatignore
Package.swift

Enable MemberImportVisibility check on all targets. Use a standard string header and footer to bracket the new block for ease of updating in the future with scripts.

Enable MemberImportVisibility check on all targets

---

Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/TaskCancellationTests.swift

swift-openapi-urlsession offers both a streaming and buffering implementation for sending/receiving data. Which implementation is used is currently based on the platform its running on, mainly because "streaming" is not supported on all platforms. It is currently not possible to "force" buffering, even if one wants/needs it.
While adding https://github.com/kean/Pulse to my app, a tool for debugging network requests, I noticed that Pulse was not showing request bodies (https://github.com/apple/swift-openapi-generator/issues/749) - because Pulse appears not do work with the streamed data mode. Neither does https://github.com/pmusolino/Wormholy.
I have now made switching .buffered mode public, allowing developers to choose which mode they want to work with. This fixes the issue I have with …

Add support for opting out of streaming HTTP bodies

---

.github/workflows/main.yml
.github/workflows/pull_request.yml
Package.swift
Sources/OpenAPIURLSession/BufferedStream/BufferedStream.swift
Sources/OpenAPIURLSession/BufferedStream/Lock.swift
Sources/OpenAPIURLSession/URLSessionTransport.swift
Tests/OpenAPIURLSessionTests/NIOAsyncHTTP1TestServer.swift

_[Explain here the context, and why you're making that change. What is the problem you're trying to solve.]_
_[Describe the modifications you've made.]_
_[After your change, what will change.]_
_[Describe the steps you took, or will take, to qualify the change - such as adjusting tests and manual testing.]_

Bump minimum Swift version to 6.0, drop 5.10 CI
